### ISSUE TITLE
I have a coding issue and would like to seek advice.

### ISSUE THREAD

**Issue by MrWan001** [kiharalab/ACC-UNet#6]
![image](https://github.com/kiharalab/ACC-UNet/assets/126931904/2c8e4e16-f1a3-48bf-b5fd-b34d94cd8876)
Here, the variable 'inv_fctr' has a value of 34, while everywhere else it is 3. Is this a mistake or intentionally set?

**Comment by nibtehaz** [comment]
Hi Wan, thank you for your interest in our project.

This value 34 was intentionally set. In Vision transformers, we know that there are comparatively more layers in the 3rd level (swin-base has like 9 times more). So we were also looking to see how 9-12 times increase impacts our model at the similar stage. 34 was giving good results during our experiments so we used that.

However, this decision is a bit problematic, because you can realize this 34 time factor substantially increases the amount of flops and overall computational requirement. For example, if you use 3 the number of params gets reduced by 2M. We are now developing a lighter and optimized version of our model and in the new version we are actually discarding this idea. The performance may slightly improve, but the computational cost is not worth that in our opinion.

**Comment by MrWan001** [comment]
I know，thank you very much.

**Comment by nibtehaz** [comment]
You're most welcome. Please let me know if you have any other queries. I am closing this issue.
